{
    helper_functions.m
    kummer_surface.m
    power_series.m
    vector_space_polynomials.m
    weil_pairing.m
    zeta_function.m
    search_local_points.m
    kummer_coordinates
    {
        find_kummer_coordinates.m
        kummer_relations.m
    }
    five_five
    {
        five_five_curves.m
    }
    richelot
    {
        richelot_on_kummer.m
        richelot_helper_functions.m
        richelot_isogeny.m
        derive_richelot_on_kummers_using_WT.m
    }
    descent
    {
        descent.m
        four_four_descent.m
        richelot_descent.m
        selmer_groups.m
        selmer_groups_general.m
    }
    torsion
    {
        difference_of_squares.m
        found_torsion_curves.m
        groebner_functions.m
        pq_functions.m
        torsion_helper_functions.m
    }
    four_four
    {
        four_four_isogeny.m
    }
}
